version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "luisgustavom1"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
