name: ci
on: pull_request

jobs:
  buiild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          
      - name: Install dependencies
        run: yarn install
        
      - name: Run lint
        run: yarn lint
        
      - name: Run tests
        run: yarn test:ci
        
      - name: Building project
        run: yarn build
